# Generated by Django 3.1.5 on 2021-03-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210306_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationships',
            name='user_follow',
        ),
        migrations.AddField(
            model_name='relationships',
            name='user_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
